# Generated by Django 3.1 on 2024-03-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_cart_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(
                blank=True, max_length=250, null=True
            ),
        ),
    ]
