# Generated by Django 3.1 on 2024-02-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="wallet",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10
            ),
        ),
    ]
