# Generated by Django 3.1 on 2024-01-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.IntegerField(default=1),
        ),
    ]
