# Generated by Django 3.1 on 2024-03-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_orderaddress_pincode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderaddress",
            old_name="phone_number",
            new_name="phone",
        ),
    ]
