# Generated by Django 3.1 on 2024-03-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_product_deleted_at"),
        ("orders", "0007_auto_20240307_1301"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.coupon",
            ),
        ),
    ]
