# Generated by Django 3.1 on 2024-03-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Accepted", "Accepted"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Refunded", "Refunded"),
                    ("Returned", "Returned"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
